FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
WORKDIR /app
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install torch torchvision \
    --index-url https://download.pytorch.org/whl/cu121
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY app_gpu.py resnet18.pth ./
ENV PYTHONUNBUFFERED=1 PORT=8000
EXPOSE 8000
CMD ["python3", "app_gpu.py"]